version: "3.3"
services:
  db:
    image: "mariadb"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports: 
      - "8081:80"
    links:
      - db:db

  wordpress:
    depends_on:
      - db
    image: "wordpress"
    restart: always
    ports: 
      - "8080:80"
    links:  
      - db:mysql
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_HOST: db:3306
